### ISSUE TITLE
Version 1.4 StartLua failing

### ISSUE THREAD

**Issue by ghost** [intveltr/vera-hue-plugin#1]
I recently installed Cree Connected bulbs and registered these on the Hue Bridge with no issues.
However, I could not get the vera hue plugin to discover these new bulbs. I uninstalled version 1.4 and reinstalled hoping that it would refresh the devices from the Hub. Now the plugin fails to load.

Here are the logs:

02  01/26/15 6:10:33.394    JobHandler::Run job#6 : dev:66 (0x120e5d0) P:50 S:0 is 6.234471000 seconds old <0x2ba39000>
06  01/26/15 6:10:33.557    Device_Variable::m_szValue_set device: 146 service: urn:intvelt-com:serviceId:HueController1 variable: LinkStatus was: Device IP is set now: Hue hub is up and linked #hooks: 0 upnp: 0 skip: 0 v:0xe27430/NONE duplicate:0 <0x2c16e680>
01  01/26/15 6:10:33.586    LuaInterface::CallFunction_Startup-1 device 146 function startup failed [string "..."]:255: attempt to perform arithmetic on field 'bri' (a nil value) <0x2c16e680>
01  01/26/15 6:10:33.586    LuImplementation::StartLua running startup code for 146 I_PhilipsHue1.xml failed <0x2c16e680>

Not sure if this is related to the Zigbee compatible Cree bulbs or something broke when I reinstalled the plugin. Kindly advise on best course of action.

**Comment by ghost** [comment]
Thanks to Ronald's help I was able to upload a newer version of I_PhillipsHue1.xml that is on the Master branch and things are working and the Cree bulbs are visible.

**Comment by intveltr** [comment]
The new version 1.5 has been published to the Vera app store and should be approved shortly.
