### ISSUE TITLE
Can no longer pair with Philips Hue after firmware update

### ISSUE THREAD

**Issue by j9brown** [intveltr/vera-hue-plugin#2]
Attempting to establish a link produces the following error:
"An unknown error occurred when linking: parameter, username, not available"

It seems the protocol has changed and is being enforced by the new firmware.

http://www.developers.meethue.com/documentation/important-whitelist-changes
http://www.developers.meethue.com/content/savant-registerdevice-error

**Comment by intveltr** [comment]
At the moment I don't have the time to address this issue; and I am not actively supporting this plugin anymore as Vera now provide an official version for UI7.  I may be able to address the issue at some later date when I have time

Van: Jeff Brown [mailto:notifications@github.com] 
Verzonden: 03 May 2016 08:02
Aan: intveltr/vera-hue-plugin
Onderwerp: [intveltr/vera-hue-plugin] Can no longer pair with Philips Hue after firmware update (#2)

Attempting to establish a link produces the following error:
"An unknown error occurred when linking: parameter, username, not available"

It seems the protocol has changed and is being enforced by the new firmware.

http://www.developers.meethue.com/documentation/important-whitelist-changes
http://www.developers.meethue.com/content/savant-registerdevice-error

**Comment by otakup0pe** [comment]
The official vera version still has this bug. If I submit a PR, are you willing to merge it ?

**Comment by intveltr** [comment]
Certainly, thanks!

**Comment by intveltr** [comment]
I got your pull request!  I hope to make some time for this tomorrow, underotunately I am not very well set up at the moment to test this extensively, but if the basic functions work, I will assume all is well and publish it on Git and the Vera app store.

Regards,

Ronald.

Van: Jonathan Freedman [mailto:notifications@github.com] 
Verzonden: 13 August 2016 19:34
Aan: intveltr/vera-hue-plugin
CC: intveltr; Comment
Onderwerp: Re: [intveltr/vera-hue-plugin] Can no longer pair with Philips Hue after firmware update (#2)

The official vera version still has this bug. If I submit a PR, are you willing to merge it ?

**Comment by otakup0pe** [comment]
Sounds good. The only testing I did on https://github.com/intveltr/vera-hue-plugin/pull/3 was seeing if I could pair on my VeraPlus, which I seem to be able to. I'm able to control the lights through the native webapp, and homewave on my ipad. My ambient lighting scripts also no longer cause the plugin to throw errors.

As I said in the PR, this probably breaks pairing on older hubs.

**Comment by intveltr** [comment]
PR is merged.

**Comment by otakup0pe** [comment]
I think you can close this out now 🎩
